@开门记录
Feature: 开门记录：上报和查询

  Scenario Outline:
    Given 用例编号<caseID>; 用例描述<description>
    When 上报开门记录: 请求参数<parameter1>, 预期结果<expected1>
    Then 查询开门记录: 请求参数<parameter2>, 预期结果<expected2>

    Examples: 开门记录的用例
      | caseID  | description                       | parameter1                                                                                                                                                                                                                                                                                                                                                                         | expected1                        | parameter2                                                                                             | expected2                                           |
      | 开门记录001 | 开门记录上报查询: 人证对比, 健康核验, 测温, 高风险     | {"deviceId": "0120100016c0aa02a00", "ways": ["FACE", "ID_NUMBER", "HEALTH_CODE", "TEMPE"], "time": None, "status": "fail", "inout": "in", "temperature": "38.55", "base64Img": r"\documents\kkk.jpg", "format": "jpg", "personId": "511028xxxx", "personName": "张正t", "uid": "", "riskAssessmentGrade": "10", "guide": "高风险", "pid": "", "cardExtension": ""}   | {"code": 200, "msg": "开门记录上报成功"} | {"startTime": None, "endTime": None, "deviceId": "0120100016c0aa02a00", "current": "1", "size": "10"}  | {"code": 200, "msg": "开门记录列表查询成功", "totalCount": 1} |
      | 开门记录002 | 开门记录上报查询: 人证对比, 健康核验, 测温, 中风险     | {"deviceId": "0120100016c0aa02a00", "ways": ["FACE", "ID_NUMBER", "HEALTH_CODE", "TEMPE"], "time": None, "status": "fail", "inout": "in", "temperature": "36.5", "base64Img": r"\documents\kkk.jpg", "format": "jpg", "personId": "51102819xxxxxxxxxx514", "personName": "张正t", "uid": "", "riskAssessmentGrade": "01", "guide": "中风险", "pid": "", "cardExtension": ""}    | {"code": 200, "msg": "开门记录上报成功"} | {"startTime": None, "endTime": None, "deviceId": "0120100016c0aa02a00", "current": "1", "size": "15"}  | {"code": 200, "msg": "开门记录列表查询成功", "totalCount": 1} |
      | 开门记录003 | 开门记录上报查询: 人证对比, 健康核验, 测温, 低风险     | {"deviceId": "0120100016c0aa02a00", "ways": ["FACE", "ID_NUMBER", "HEALTH_CODE", "TEMPE"], "time": None, "status": "success", "inout": "in", "temperature": "36.5", "base64Img": r"\documents\ttt.jpg", "format": "jpg", "personId": "5110281xxxxxxxxxxxxx88514", "personName": "张正t", "uid": "", "riskAssessmentGrade": "00", "guide": "低风险", "pid": "", "cardExtension": ""} | {"code": 200, "msg": "开门记录上报成功"} | {"startTime": None, "endTime": None, "deviceId": "0120100016c0aa02a00", "current": "1", "size": "20"}  | {"code": 200, "msg": "开门记录列表查询成功", "totalCount": 1} |
      | 开门记录004 | 开门记录上报查询: 扫码核验(高风险), 测温           | {"deviceId": "0120100016c0aa02a00", "ways": ["HEALTH_CODE", "TEMPE"], "time": None, "status": "fail", "inout": "in", "temperature": "38.00", "personId": "", "personName": "", "uid": "", "riskAssessmentGrade": "10", "guide": "高风险", "pid": "", "cardExtension": ""}                                                                              | {"code": 200, "msg": "开门记录上报成功"} | {"startTime": None, "endTime": None, "deviceId": "0120100016c0aa02a00", "current": "1", "size": "30"}  | {"code": 200, "msg": "开门记录列表查询成功", "totalCount": 1} |
      | 开门记录005 | 开门记录上报查询: 扫码核验(中风险), 测温           | {"deviceId": "0120100016c0aa02a00", "ways": ["HEALTH_CODE", "TEMPE"], "time": None, "status": "fail", "inout": "in", "temperature": "38.00", "format": "", "personId": "", "personName": "", "uid": "", "riskAssessmentGrade": "01", "guide": "中风险", "pid": "", "cardExtension": ""}                                                                              | {"code": 200, "msg": "开门记录上报成功"} | {"startTime": None, "endTime": None, "deviceId": "0120100016c0aa02a00", "current": "1", "size": "40"}  | {"code": 200, "msg": "开门记录列表查询成功", "totalCount": 1} |
      | 开门记录006 | 开门记录上报查询: 扫码核验(低风险), 测温           | {"deviceId": "0120100016c0aa02a00", "ways": ["HEALTH_CODE", "TEMPE"], "time": None, "status": "success", "inout": "in", "temperature": "36", "format": "", "personId": "", "personName": "", "uid": "", "riskAssessmentGrade": "00", "guide": "低风险", "pid": "", "cardExtension": ""}                                                                              | {"code": 200, "msg": "开门记录上报成功"} | {"startTime": None, "endTime": None, "deviceId": "0120100016c0aa02a00", "current": "1", "size": "50"}  | {"code": 200, "msg": "开门记录列表查询成功", "totalCount": 1} |
      | 开门记录007 | 开门记录上报查询: 刷卡, 测温(高温)              | {"deviceId": "0120100016c0aa02a00", "ways": ["IC_CARD", "TEMPE"], "time": None, "status": "fail", "inout": "in", "temperature": "38", "format": "", "personId": "", "personName": "", "uid": "8776EAE0", "riskAssessmentGrade": "", "guide": "", "pid": "", "cardExtension": ""}                                                                                  | {"code": 200, "msg": "开门记录上报成功"} | {"startTime": None, "endTime": None, "deviceId": "0120100016c0aa02a00", "current": "1", "size": "100"} | {"code": 200, "msg": "开门记录列表查询成功", "totalCount": 1} |
      | 开门记录008 | 开门记录上报查询: 刷卡, 测温(常温)              | {"deviceId": "0120100016c0aa02a00", "ways": ["IC_CARD", "TEMPE"], "time": None, "status": "success", "inout": "in", "temperature": "36", "format": "", "personId": "", "personName": "", "uid": "8776EBE0", "riskAssessmentGrade": "", "guide": "", "pid": "", "cardExtension": ""}                                                                               | {"code": 200, "msg": "开门记录上报成功"} | {"startTime": None, "endTime": None, "deviceId": "0120100016c0aa02a00", "current": "1", "size": "10"}  | {"code": 200, "msg": "开门记录列表查询成功", "totalCount": 1} |
      | 开门记录009 | 开门记录上报查询: 健康核验(中风险), 黄码通行, 测温(常温) | {"deviceId": "0120100016c0aa02a00", "ways": ["HEALTH_CODE", "YELLOW_CODE", "TEMPE"], "time": None, "status": "success", "inout": "in", "temperature": "36", "format": "", "personId": "", "personName": "", "uid": "", "riskAssessmentGrade": "01", "guide": "黄码, 可以通行", "pid": "", "cardExtension": ""}                                                          | {"code": 200, "msg": "开门记录上报成功"} | {"startTime": None, "endTime": None, "deviceId": "0120100016c0aa02a00", "current": "1", "size": "10"}  | {"code": 200, "msg": "开门记录列表查询成功", "totalCount": 1} |
      | 开门记录010 | 开门记录上报查询: 健康核验(高风险), 黄码通行, 测温(高温) | {"deviceId": "0120100016c0aa02a00", "ways": ["HEALTH_CODE", "YELLOW_CODE", "TEMPE"], "time": None, "status": "fail", "inout": "in", "temperature": "38", "format": "", "personId": "", "personName": "", "uid": "", "riskAssessmentGrade": "10", "guide": "红码,不可通行", "pid": "", "cardExtension": ""}                                                              | {"code": 200, "msg": "开门记录上报成功"} | {"startTime": None, "endTime": None, "deviceId": "0120100016c0aa02a00", "current": "1", "size": "10"}  | {"code": 200, "msg": "开门记录列表查询成功", "totalCount": 1} |
      | 开门记录011 | 开门记录上报查询: 门禁盒子刷卡开门 | {"deviceId": "FE990A0F", "ways": ["IC_CARD"], "time": None, "status": "success", "inout": "in", "temperature": "", "format": "", "personId": "", "personName": "", "uid": "8776EAE0", "riskAssessmentGrade": "", "guide": "", "pid": "", "cardExtension": ""}                                                              | {"code": 200, "msg": "开门记录上报成功"} | {"startTime": None, "endTime": None, "deviceId": "FE990A0F", "current": "1", "size": "10"}  | {"code": 200, "msg": "开门记录列表查询成功", "totalCount": 1} |