@指令下发
Feature: instruction issuance

  Scenario Outline: all instructions
    Given 用例<caseID>描述<description>
    When 参数准备: 请求头
    Then 下发指令: 接口<api1>请求参数<parameter1>期望值<expected1>
    Then 心跳接收: 接口<api2>请求参数<parameter2>期望值<expected2>
    Then 任务执行: 接口<api3>任务反馈<feedback>期望值<expected3>
    Then 指令查询: 接口<api4>请求参数<parameter4>期望值<expected4>

#    Examples: 所有可能的指令
#      | caseID  | tag        | deviceId            | deviceName | name   | instruction | instruParams | sendType | retryCount | feedback |
#      | case001 | tag_结果展示时长 | 0120100016c0aa02a00 | 设备002      | 结果展示时长 | 2002        | {"time": 3}  | http     | 0          | success  |
#      | case002 | tag_重启设备   | 0120100016c0aa02a00 | 设备002 | 重启设备   | 3001        | {}           | http     | 0          | success  |
#      | case003 | tag_固件升级   | 0120100016c0aa02a00 | 设备002      | 固件升级   | 4001        | {"url": "https://www.baidu.com", "version": "v1.0"}    | http     | 0          | success  |
#      | case004 | tag_切换服务器   | 0120100016c0aa02a00 | 设备002      | 设置服务器地址   | 4003        | {"server": "www.baidu.com:555", "api_key": "ugp1zdjvhfsht16a", "api_secret": "0eb9trdq29yj8q7ruc0nrokm4obstd7s"}    | http     | 0          | success  |
#      | case005 | tag_下发人员信息   | 0120100016c0aa02a00 | 设备002   | 下发人员信息   | 4002  | {"operationType": "add", "personId": "5", "personName": "张正涛", "uid": "AA3E34F7", "cardType": "M1", "base64Img": 0, "format": "png", "type": "USER", "isInBlackList": True} | http  | 0  | success  |
#      | case006 | tag_修改人员信息   | 0120100016c0aa02a00 | 设备002   | 下发人员信息   | 4002  | {"operationType": "update", "personId": "511028199603088510", "personName": "张正涛", "uid": "AA3E34F7", "cardType": "CPU", "base64Img": 0, "format": "jpg", "type": "ADMIN", "isInBlackList": False} | http  | 0  | success  |
#      | case007 | tag_   | 0120100016c0aa02a00 | 设备002   | 下发人员信息   | 4002  | {"operationType": "delete", "personId": "511028199603088510", "personName": "张正涛", "uid": "AA3E34F7", "cardType": "CPU", "base64Img": None, "format": "jpg", "type": "ADMIN", "isInBlackList": False} | http  | 0  | success  |
#      | case008 | tag_查询人员信息   | 0120100016c0aa02a00 | 设备002   | 下发人员信息   | 4002  | {"operationType": "select", "personId": "511028199603088510", "personName": "张正涛", "uid": "AA3E34F7", "cardType": "CPU", "base64Img": None, "format": "jpg", "type": "ADMIN", "isInBlackList": False} | http  | 0  | success  |
#      | case009 | tag_下发权限   | 0120100016c0aa02a00 | 设备002   | 下发人员信息   | 4002  | {"operationType": "add", "personId": "", "personName": "张正涛", "uid": "AA3E34F7", "cardType": "MAC", "base64Img": , "format": "", "type": "", "isInBlackList": False} | tcp  | 0  | success  |
#      | case010 | tag_门禁策略   | 0120100016c0aa02a00 | 设备002   | 下发人员信息   | 4002  | {"operationType": "add", "personId": "", "personName": "张正涛", "uid": "AA3E34F7", "cardType": "MAC", "base64Img": , "format": "", "type": "", "isInBlackList": False} | tcp  | 0  | success  |
#      | case010 | tag_门禁策略   | 0120100016c0aa02a00 | 设备002   | 下发人员信息   | 4002  | {"operationType": "add", "personId": "", "personName": "张正涛", "uid": "AA3E34F7", "cardType": "MAC", "base64Img": , "format": "", "type": "", "isInBlackList": False} | tcp  | 0  | success  |


    Examples: 新用例
      | caseID  | description    | api1                            | parameter1                                                                                                                                                                                                                                                                                                                                                                                               | expected1                      | api2                            | parameter2                          | expected2                        | api3                            | feedback | expected3                      | api4                           | parameter4                            | expected4                                    |
      | 指令下发001 | 下发指令: 结果展示时长3秒 | {"接口名": "指令下发", "请求方法": "POST"} | [{"tag": "tag_结果展示时长", "deviceId": "0120100016c0aa02a00", "deviceName": "设备002", "name": "结果展示时长", "instruction": "2002", "instruParams": {"time": 3}, "sendType": "http", "retryCount": 0}]                                                                                                                                                                                                             | {"code": 200, "msg": "指令下发成功"} | {"接口名": "设备心跳", "请求方法": "POST"} | {"deviceId": "0120100016c0aa02a00"} | {"code": 200, "msg": "设备心跳上报成功"} | {"接口名": "任务跟踪", "请求方法": "POST"} | success  | {"code": 200, "msg": "任务跟踪成功"} | {"接口名": "指令查询", "请求方法": "GET"} | {"status": "COMPLETED", "current": 1} | {"code": 200, "msg": "指令列表查询成功", "total": 1} |
      | 指令下发002 | 下发指令: 重启设备     | {"接口名": "指令下发", "请求方法": "POST"} | [{"tag": "tag重启设备", "deviceId": "0120100016c0aa02a00", "deviceName": "设备002", "name": "重启设备", "instruction": "2002", "instruParams": {}, "sendType": "http", "retryCount": 0}]                                                                                                                                                                                                                           | {"code": 200, "msg": "指令下发成功"} | {"接口名": "设备心跳", "请求方法": "POST"} | {"deviceId": "0120100016c0aa02a00"} | {"code": 200, "msg": "设备心跳上报成功"} | {"接口名": "任务跟踪", "请求方法": "POST"} | success  | {"code": 200, "msg": "任务跟踪成功"} | {"接口名": "指令查询", "请求方法": "GET"} | {"status": "COMPLETED", "current": 1} | {"code": 200, "msg": "指令列表查询成功", "total": 1} |
      | 指令下发003 | 下发指令: 固件升级     | {"接口名": "指令下发", "请求方法": "POST"} | [{"tag": "tag固件升级", "deviceId": "0120100016c0aa02a00", "deviceName": "设备002", "name": "远程升级", "instruction": "4001", "instruParams": {"url": "https://www.baidu.com", "version": "v1.0"}, "sendType": "http", "retryCount": 0}]                                                                                                                                                                          | {"code": 200, "msg": "指令下发成功"} | {"接口名": "设备心跳", "请求方法": "POST"} | {"deviceId": "0120100016c0aa02a00"} | {"code": 200, "msg": "设备心跳上报成功"} | {"接口名": "任务跟踪", "请求方法": "POST"} | success  | {"code": 200, "msg": "任务跟踪成功"} | {"接口名": "指令查询", "请求方法": "GET"} | {"status": "COMPLETED", "current": 1} | {"code": 200, "msg": "指令列表查询成功", "total": 1} |
      | 指令下发004 | 下发指令: 换服务器     | {"接口名": "指令下发", "请求方法": "POST"} | [{"tag": "tag换个服务器", "deviceId": "0120100016c0aa02a00", "deviceName": "设备002", "name": "切换服务器", "instruction": "4003", "instruParams": {"server": "www.baidu.com:555", "api_key": "ugp1zdjvhfsht16a", "api_secret": "0eb9trdq29yj8q7ruc0nrokm4obstd7s"} , "sendType": "http", "retryCount": 0}]                                                                                                          | {"code": 200, "msg": "指令下发成功"} | {"接口名": "设备心跳", "请求方法": "POST"} | {"deviceId": "0120100016c0aa02a00"} | {"code": 200, "msg": "设备心跳上报成功"} | {"接口名": "任务跟踪", "请求方法": "POST"} | success  | {"code": 200, "msg": "任务跟踪成功"} | {"接口名": "指令查询", "请求方法": "GET"} | {"status": "COMPLETED", "current": 1} | {"code": 200, "msg": "指令列表查询成功", "total": 1} |
      | 指令下发005 | 下发指令: 下发人员信息   | {"接口名": "指令下发", "请求方法": "POST"} | [{"tag": "tag下发一个人员信息", "deviceId": "0120100016c0aa02a00", "deviceName": "设备002", "name": "下发人员信息", "instruction": "4002", "instruParams": {"operationType": "add", "personId": "511028199603080010", "personName": "张正涛", "uid": "AA3E34F7", "cardType": "M1", "base64Img": r"/documents/kkk.jpg", "format": "png", "type": "USER", "isInBlackList": True}, "sendType": "http", "retryCount": 0}]       | {"code": 200, "msg": "指令下发成功"} | {"接口名": "设备心跳", "请求方法": "POST"} | {"deviceId": "0120100016c0aa02a00"} | {"code": 200, "msg": "设备心跳上报成功"} | {"接口名": "任务跟踪", "请求方法": "POST"} | success  | {"code": 200, "msg": "任务跟踪成功"} | {"接口名": "指令查询", "请求方法": "GET"} | {"status": "COMPLETED", "current": 1} | {"code": 200, "msg": "指令列表查询成功", "total": 1} |
      | 指令下发006 | 下发指令: 修改人员信息   | {"接口名": "指令下发", "请求方法": "POST"} | [{"tag": "tag修改一个人员信息", "deviceId": "0120100016c0aa02a00", "deviceName": "设备002", "name": "下发人员信息", "instruction": "4002", "instruParams": {"operationType": "update", "personId": "511028199603080010", "personName": "张正涛", "uid": "AA3E34F7", "cardType": "CPU", "base64Img": r"/documents/ttt.jpg", "format": "jpg", "type": "ADMIN", "isInBlackList": False}, "sendType": "http", "retryCount": 0}] | {"code": 200, "msg": "指令下发成功"} | {"接口名": "设备心跳", "请求方法": "POST"} | {"deviceId": "0120100016c0aa02a00"} | {"code": 200, "msg": "设备心跳上报成功"} | {"接口名": "任务跟踪", "请求方法": "POST"} | success  | {"code": 200, "msg": "任务跟踪成功"} | {"接口名": "指令查询", "请求方法": "GET"} | {"status": "COMPLETED", "current": 1} | {"code": 200, "msg": "指令列表查询成功", "total": 1} |
      | 指令下发007 | 下发指令: 删除人员信息   | {"接口名": "指令下发", "请求方法": "POST"} | [{"tag": "tag删除一个人员信息", "deviceId": "0120100016c0aa02a00", "deviceName": "设备002", "name": "下发人员信息", "instruction": "4002", "instruParams": {"operationType": "delete", "personId": "511028199603080010", "personName": "张正涛", "type": "ADMIN", "isInBlackList": False}, "sendType": "http", "retryCount": 0}]                                                                                            | {"code": 200, "msg": "指令下发成功"} | {"接口名": "设备心跳", "请求方法": "POST"} | {"deviceId": "0120100016c0aa02a00"} | {"code": 200, "msg": "设备心跳上报成功"} | {"接口名": "任务跟踪", "请求方法": "POST"} | success  | {"code": 200, "msg": "任务跟踪成功"} | {"接口名": "指令查询", "请求方法": "GET"} | {"status": "COMPLETED", "current": 1} | {"code": 200, "msg": "指令列表查询成功", "total": 1} |
      | 指令下发008 | 下发指令: 查询人员信息   | {"接口名": "指令下发", "请求方法": "POST"} | [{"tag": "tag查询人员信息", "deviceId": "0120100016c0aa02a00", "deviceName": "设备002", "name": "下发人员信息", "instruction": "4002", "instruParams": {"operationType": "select", "personId": "511028199603080010", "personName": "张正涛", "uid": "AA3E34F7", "cardType": "CPU", "type": "ADMIN", "isInBlackList": False}, "sendType": "http", "retryCount": 0}]                                                        | {"code": 200, "msg": "指令下发成功"} | {"接口名": "设备心跳", "请求方法": "POST"} | {"deviceId": "0120100016c0aa02a00"} | {"code": 200, "msg": "设备心跳上报成功"} | {"接口名": "任务跟踪", "请求方法": "POST"} | success  | {"code": 200, "msg": "任务跟踪成功"} | {"接口名": "指令查询", "请求方法": "GET"} | {"status": "COMPLETED", "current": 1} | {"code": 200, "msg": "指令列表查询成功", "total": 1} |
      | 指令下发009 | 下发指令: 下发权限     | {"接口名": "指令下发", "请求方法": "POST"} | [{"tag": "tag下发权限", "deviceId": "0120100016c0aa02a00", "deviceName": "设备002", "name": "下发人员信息", "instruction": "4002", "instruParams": {"operationType": "add", "personName": "张正涛", "uid": "AA3E34F7", "cardType": "MAC", "isInBlackList": False}, "sendType": "tcp", "retryCount": 0}]                                                                                                                 | {"code": 200, "msg": "指令下发成功"} | {"接口名": "设备心跳", "请求方法": "POST"} | {"deviceId": "0120100016c0aa02a00"} | {"code": 200, "msg": "设备心跳上报成功"} | {"接口名": "任务跟踪", "请求方法": "POST"} | success  | {"code": 200, "msg": "任务跟踪成功"} | {"接口名": "指令查询", "请求方法": "GET"} | {"status": "COMPLETED", "current": 1} | {"code": 200, "msg": "指令列表查询成功", "total": 1} |